### ISSUE TITLE
自定义1080P分辨率视频录制,点击开始录制，获取录音权限后,闪退出录制界面

### ISSUE THREAD

**Issue by heyzhuyue** [umdk/UCDLive_Android#11]
@tanliwen 
抛出异常:
```
AndroidRuntime: FATAL EXCEPTION: VideoSenderThread
                                                                          Process: com.ucloud.ulive.example, PID: 12924
                                                                          java.lang.IllegalStateException
                                                                              at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
                                                                              at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2392)
                                                                              at com.ucloud.ulive.av.video.e.run(SourceFile:1074)
```
麻烦解决一下

**Comment by tanliwen** [comment]
@heyzhuyue 
1.确认是否其它分辨率能否正常支持，若其它支持，1080p有问题，说明该设备存在兼容性问题，硬编码调用的是系统API，高效但是存在兼容性问题，没有一种方案能保证在所有机器上没有问题。
2.推荐用软编做兼容覆盖。
3.反馈问题尽量按照 https://github.com/umdk/UCDLive_Android#问题反馈参考模板
