### ISSUE TITLE
imx6 android 4.3 

### ISSUE THREAD

**Issue by yanghui1** [umdk/UCDLive_Android#15]
下载的demo安装ulive-demo-debug.apk 后点击demo publish按钮后退出， android 4.3系统，usb 摄像头，
这个demo apk 在android 4.4 系统上ok , 
logcat：
E/FastMixer( 3699): did not receive expected priority boost
W/audio_hw_primary( 3699): card 2, port 0 device 0x400
W/audio_hw_primary( 3699): rate 44100, channel 2 period_size 0x300
I/ActivityManager( 2577): START u0 {act=ucloud.intent.action.ulive.example.publish cmp=com.ucloud.ulive.example/.PublishDemo (has extras)} from pid 4283
E/BufferQueue( 2577): [ScreenshotClient] dequeueBuffer: can't dequeue multiple buffers without setting the buffer count
V/WindowManager( 2577): Skipping AppWindowToken{41cd6020 token=Token{41a60440 ActivityRecord{41eca610 u0 com.ucloud.ulive.example/.PublishDemo}}} -- hidden on top
V/WindowManager( 2577): Done at AppWindowToken{420d17d8 token=Token{42067c00 ActivityRecord{41bcf4d8 u0 com.ucloud.ulive.example/.MainActivity}}} -- full screen, return 4
V/WindowManager( 2577): Skipping set freeze of Token{41a60440 ActivityRecord{41eca610 u0 com.ucloud.ulive.example/.PublishDemo}}
V/WindowManager( 2577): setAppVisibility(Token{41a60440 ActivityRecord{41eca610 u0 com.ucloud.ulive.example/.PublishDemo}}, visible=true): mNextAppTransition=0x1006 hidden=true hiddenRequested=true
V/WindowManager( 2577): Done at AppWindowToken{41cd6020 token=Token{41a60440 ActivityRecord{41eca610 u0 com.ucloud.ulive.example/.PublishDemo}}} -- full screen, return -1
V/WindowManager( 2577): Application requested orientation -1, got rotation 3 which has compatible metrics
V/WindowManager( 2577): setAppVisibility(Token{42067c00 ActivityRecord{41bcf4d8 u0 com.ucloud.ulive.example/.MainActivity}}, visible=false): mNextAppTransition=0x1006 hidden=false hiddenRequested=false
I/WindowStateAnimator( 2577): createSurface WindowStateAnimator{41c80610 Toast}: mDrawState=DRAW_PENDING
V/WindowManager( 2577): Done at AppWindowToken{41cd6020 token=Token{41a60440 ActivityRecord{41eca610 u0 com.ucloud.ulive.example/.PublishDemo}}} -- full screen, return -1
V/WindowManager( 2577): Resize reasons:  contentInsetsChanged=false [0,0][0,0] visibleInsetsChanged=false [0,0][0,0] surfaceResized=true configChanged=true
V/WindowManager( 2577): Resizing window Window{41c05070 u0 Toast} to 160.0x51.0
V/WindowManager( 2577): Reporting new frame to Window{41c05070 u0 Toast}: Rect(460, 1805 - 620, 1856)
I/WindowManager( 2577): Sending new config to window Window{41c05070 u0 Toast}: 160.0x51.0 / {1.0 ?mcc?mnc zh_CN ldltr sw1080dp w1080dp h1920dp 160dpi xlrg long port -touch -keyb/v/h dpad/v s.5} / 0x0
I/WindowManager( 2577): Resizing Window{41c05070 u0 Toast} WITH DRAW PENDING
D/dalvikvm( 4283): GC_CONCURRENT freed 178K, 7% free 3396K/3632K, paused 3ms+4ms, total 29ms
I/ulive-demo( 4283): lifecycle->demo->config->filter = 1, orientation = 1, fps = 20 bitrate = 400 resolution = captureWidth=0
I/ulive-demo( 4283): captureHeight=0
I/ulive-demo( 4283): outputWidth=0
I/ulive-demo( 4283): outputHeight=0
V/WindowManager( 2577): Done at AppWindowToken{41cd6020 token=Token{41a60440 ActivityRecord{41eca610 u0 com.ucloud.ulive.example/.PublishDemo}}} -- full screen, return 1
V/WindowManager( 2577): Application requested orientation 1, got rotation 3 which has compatible metrics
W/audio_hw_primary( 3699): get_input_buffer_size size = 192, channel_count = 2
W/audio_hw_primary( 3699): In channels 2, rate 8000, devices 0x80001000
W/audio_hw_primary( 3699): card 0, id C170 ,driver USB-Audio, name Webcam C170
W/audio_hw_primary( 3699): out rate 0
W/audio_hw_primary( 3699): in rate 44100, channels 1 format 0
W/audio_hw_primary( 3699): card 1, id wm8962audio ,driver wm8962-audio, name wm8962-audio
W/audio_hw_primary( 3699): card 2, id imxhdmisoc ,driver imx-hdmi-soc, name imx-hdmi-soc
W/audio_hw_primary( 3699): get_input_buffer_size size = 192, channel_count = 2
W/audio_hw_primary( 3699): get_input_buffer_size size = 384, channel_count = 2
W/AudioPolicyManagerBase( 3699): unregisterEffect() unknown effect ID 21
W/AudioPolicyManagerBase( 3699): unregisterEffect() unknown effect ID 22
W/AudioPolicyManagerBase( 3699): unregisterEffect() unknown effect ID 23
W/AudioFlinger( 3699): removeEffect_l() 0x40d1d360 cannot promote chain for effect 0x40d2ce48
W/AudioPolicyManagerBase( 3699): unregisterEffect() unknown effect ID 21
W/AudioFlinger( 3699): removeEffect_l() 0x40d1d360 cannot promote chain for effect 0x40118c80
W/AudioPolicyManagerBase( 3699): unregisterEffect() unknown effect ID 22
W/AudioFlinger( 3699): removeEffect_l() 0x40d1d360 cannot promote chain for effect 0x411640f0
W/AudioPolicyManagerBase( 3699): unregisterEffect() unknown effect ID 23
W/audio_hw_primary( 3699): In channels 2, rate 16000, devices 0x80001000
W/audio_hw_primary( 3699): card 0, id C170 ,driver USB-Audio, name Webcam C170
W/audio_hw_primary( 3699): out rate 0
W/audio_hw_primary( 3699): in rate 44100, channels 1 format 0
W/audio_hw_primary( 3699): card 1, id wm8962audio ,driver wm8962-audio, name wm8962-audio
W/audio_hw_primary( 3699): card 2, id imxhdmisoc ,driver imx-hdmi-soc, name imx-hdmi-soc
W/audio_hw_primary( 3699): get_input_buffer_size size = 384, channel_count = 2
W/AudioPolicyManagerBase( 3699): unregisterEffect() unknown effect ID 26
W/AudioPolicyManagerBase( 3699): unregisterEffect() unknown effect ID 27
W/AudioPolicyManagerBase( 3699): unregisterEffect() unknown effect ID 28
W/AudioFlinger( 3699): removeEffect_l() 0x40d2ce18 cannot promote chain for effect 0x40ef5920
W/audio_hw_primary( 3699): get_input_buffer_size size = 256, channel_count = 2
W/AudioPolicyManagerBase( 3699): unregisterEffect() unknown effect ID 26
W/AudioFlinger( 3699): removeEffect_l() 0x40d2ce18 cannot promote chain for effect 0x40ef5c18
W/AudioPolicyManagerBase( 3699): unregisterEffect() unknown effect ID 27
W/AudioFlinger( 3699): removeEffect_l() 0x40d2ce18 cannot promote chain for effect 0x41164ad8
W/AudioPolicyManagerBase( 3699): unregisterEffect() unknown effect ID 28
W/audio_hw_primary( 3699): In channels 2, rate 11025, devices 0x80001000
W/audio_hw_primary( 3699): card 0, id C170 ,driver USB-Audio, name Webcam C170
W/audio_hw_primary( 3699): out rate 0
W/audio_hw_primary( 3699): in rate 44100, channels 1 format 0
W/audio_hw_primary( 3699): card 1, id wm8962audio ,driver wm8962-audio, name wm8962-audio
W/audio_hw_primary( 3699): card 2, id imxhdmisoc ,driver imx-hdmi-soc, name imx-hdmi-soc
W/audio_hw_primary( 3699): get_input_buffer_size size = 256, channel_count = 2
W/audio_hw_primary( 3699): get_input_buffer_size size = 512, channel_count = 2
W/audio_hw_primary( 3699): In channels 2, rate 22050, devices 0x80001000
W/audio_hw_primary( 3699): card 0, id C170 ,driver USB-Audio, name Webcam C170
W/audio_hw_primary( 3699): out rate 0
W/audio_hw_primary( 3699): in rate 44100, channels 1 format 0
W/audio_hw_primary( 3699): card 1, id wm8962audio ,driver wm8962-audio, name wm8962-audio
W/audio_hw_primary( 3699): card 2, id imxhdmisoc ,driver imx-hdmi-soc, name imx-hdmi-soc
W/audio_hw_primary( 3699): get_input_buffer_size size = 512, channel_count = 2
W/AudioPolicyManagerBase( 3699): unregisterEffect() unknown effect ID 31
W/AudioPolicyManagerBase( 3699): unregisterEffect() unknown effect ID 32
W/AudioPolicyManagerBase( 3699): unregisterEffect() unknown effect ID 33
W/AudioFlinger( 3699): removeEffect_l() 0x40d2ce18 cannot promote chain for effect 0x41144008
W/AudioPolicyManagerBase( 3699): unregisterEffect() unknown effect ID 31
W/AudioFlinger( 3699): removeEffect_l() 0x40d2ce18 cannot promote chain for effect 0x40d2ee38
W/AudioPolicyManagerBase( 3699): unregisterEffect() unknown effect ID 32
W/AudioFlinger( 3699): removeEffect_l() 0x40d2ce18 cannot promote chain for effect 0x40f00da0
W/AudioPolicyManagerBase( 3699): unregisterEffect() unknown effect ID 33
W/audio_hw_primary( 3699): get_input_buffer_size size = 1024, channel_count = 2
W/AudioPolicyManagerBase( 3699): unregisterEffect() unknown effect ID 36
W/AudioPolicyManagerBase( 3699): unregisterEffect() unknown effect ID 37
W/AudioPolicyManagerBase( 3699): unregisterEffect() unknown effect ID 38
W/AudioFlinger( 3699): removeEffect_l() 0x41164880 cannot promote chain for effect 0x40172008
W/AudioPolicyManagerBase( 3699): unregisterEffect() unknown effect ID 36
W/AudioFlinger( 3699): removeEffect_l() 0x41164880 cannot promote chain for effect 0x417249b0
W/AudioPolicyManagerBase( 3699): unregisterEffect() unknown effect ID 37
W/AudioFlinger( 3699): removeEffect_l() 0x41164880 cannot promote chain for effect 0x411f4e60
W/AudioPolicyManagerBase( 3699): unregisterEffect() unknown effect ID 38
W/audio_hw_primary( 3699): In channels 2, rate 44100, devices 0x80001000
W/audio_hw_primary( 3699): card 0, id C170 ,driver USB-Audio, name Webcam C170
W/audio_hw_primary( 3699): out rate 0
W/audio_hw_primary( 3699): in rate 44100, channels 1 format 0
W/audio_hw_primary( 3699): card 1, id wm8962audio ,driver wm8962-audio, name wm8962-audio
W/audio_hw_primary( 3699): card 2, id imxhdmisoc ,driver imx-hdmi-soc, name imx-hdmi-soc
W/audio_hw_primary( 3699): get_input_buffer_size size = 1024, channel_count = 2
I/InputDispatcher( 2577): Dropping event because there is no touched window.
I/InputDispatcher( 2577): Dropping event because there is no touched window.
I/InputDispatcher( 2577): Dropping event because there is no touched window.
I/InputDispatcher( 2577): Dropping event because there is no touched window.
I/InputDispatcher( 2577): Dropping event because there is no touched window.
I/InputDispatcher( 2577): Dropping event because there is no touched window.
I/InputDispatcher( 2577): Dropping event because there is no touched window.
I/InputDispatcher( 2577): Dropping event because there is no touched window.
I/InputDispatcher( 2577): Dropping event because there is no touched window.
I/InputDispatcher( 2577): Dropping event because there is no touched window.
I/InputDispatcher( 2577): Dropping event because there is no touched window.
I/InputDispatcher( 2577): Dropping event because there is no touched window.
I/InputDispatcher( 2577): Dropping event because there is no touched window.
I/InputDispatcher( 2577): Dropping event because there is no touched window.
I/InputDispatcher( 2577): Dropping event because there is no touched window.
W/audio_hw_primary( 3699): get_input_buffer_size size = 1120, channel_count = 2
W/AudioPolicyManagerBase( 3699): unregisterEffect() unknown effect ID 41
W/AudioPolicyManagerBase( 3699): unregisterEffect() unknown effect ID 42
W/AudioPolicyManagerBase( 3699): unregisterEffect() unknown effect ID 43
W/AudioFlinger( 3699): removeEffect_l() 0x40ef55d0 cannot promote chain for effect 0x41145480
W/AudioPolicyManagerBase( 3699): unregisterEffect() unknown effect ID 41
W/AudioFlinger( 3699): removeEffect_l() 0x40ef55d0 cannot promote chain for effect 0x40ef5df8
W/AudioPolicyManagerBase( 3699): unregisterEffect() unknown effect ID 42
W/AudioFlinger( 3699): removeEffect_l() 0x40ef55d0 cannot promote chain for effect 0x40d2ee38
W/AudioPolicyManagerBase( 3699): unregisterEffect() unknown effect ID 43
W/audio_hw_primary( 3699): In channels 2, rate 48000, devices 0x80001000
W/audio_hw_primary( 3699): card 0, id C170 ,driver USB-Audio, name Webcam C170
W/audio_hw_primary( 3699): out rate 0
W/audio_hw_primary( 3699): in rate 44100, channels 1 format 0
W/audio_hw_primary( 3699): card 1, id wm8962audio ,driver wm8962-audio, name wm8962-audio
W/audio_hw_primary( 3699): card 2, id imxhdmisoc ,driver imx-hdmi-soc, name imx-hdmi-soc
W/audio_hw_primary( 3699): get_input_buffer_size size = 1120, channel_count = 2
I/ulive-demo( 4283): lifecycle->demo->support samplerates->[8000, 16000, 11025, 22050, 44100, 48000]
W/AudioPolicyManagerBase( 3699): unregisterEffect() unknown effect ID 46
W/AudioPolicyManagerBase( 3699): unregisterEffect() unknown effect ID 47
W/AudioPolicyManagerBase( 3699): unregisterEffect() unknown effect ID 48
W/AudioFlinger( 3699): removeEffect_l() 0x40ef55d0 cannot promote chain for effect 0x41145d60
W/AudioPolicyManagerBase( 3699): unregisterEffect() unknown effect ID 46
W/AudioFlinger( 3699): removeEffect_l() 0x40ef55d0 cannot promote chain for effect 0x40f02ba0
W/AudioPolicyManagerBase( 3699): unregisterEffect() unknown effect ID 47
W/AudioFlinger( 3699): removeEffect_l() 0x40ef55d0 cannot promote chain for effect 0x40118970
W/AudioPolicyManagerBase( 3699): unregisterEffect() unknown effect ID 48
W/audio_hw_primary( 3699): get_input_buffer_size size = 1024, channel_count = 2
W/audio_hw_primary( 3699): In channels 2, rate 44100, devices 0x80001000
W/audio_hw_primary( 3699): card 0, id C170 ,driver USB-Audio, name Webcam C170
W/audio_hw_primary( 3699): out rate 0
W/audio_hw_primary( 3699): in rate 44100, channels 1 format 0
W/audio_hw_primary( 3699): card 1, id wm8962audio ,driver wm8962-audio, name wm8962-audio
W/audio_hw_primary( 3699): card 2, id imxhdmisoc ,driver imx-hdmi-soc, name imx-hdmi-soc
W/audio_hw_primary( 3699): get_input_buffer_size size = 1024, channel_count = 2
I/InputDispatcher( 2577): Dropping event because there is no touched window.
I/InputDispatcher( 2577): Dropping event because there is no touched window.
I/InputDispatcher( 2577): Dropping event because there is no touched window.
I/InputDispatcher( 2577): Dropping event because there is no touched window.
I/InputDispatcher( 2577): Dropping event because there is no touched window.
I/InputDispatcher( 2577): Dropping event because there is no touched window.
I/InputDispatcher( 2577): Dropping event because there is no touched window.
W/AudioPolicyManagerBase( 3699): unregisterEffect() unknown effect ID 51
W/AudioPolicyManagerBase( 3699): unregisterEffect() unknown effect ID 52
W/AudioPolicyManagerBase( 3699): unregisterEffect() unknown effect ID 53
W/AudioFlinger( 3699): removeEffect_l() 0x40ef55d0 cannot promote chain for effect 0x41144378
W/AudioPolicyManagerBase( 3699): unregisterEffect() unknown effect ID 51
W/AudioFlinger( 3699): removeEffect_l() 0x40ef55d0 cannot promote chain for effect 0x40d2ee38
W/AudioPolicyManagerBase( 3699): unregisterEffect() unknown effect ID 52
W/AudioFlinger( 3699): removeEffect_l() 0x40ef55d0 cannot promote chain for effect 0x40118d98
W/AudioPolicyManagerBase( 3699): unregisterEffect() unknown effect ID 53
I/InputDispatcher( 2577): Dropping event because there is no touched window.
I/InputDispatcher( 2577): Dropping event because there is no touched window.
E/UEasyStreaming( 4283): java.lang.NullPointerException->Brand=Freescale&Model=SABRESD-MX6DQ&Android=18&SdkVersion=1.5.0
I/ulive-demo( 4283): lifecycle->demo->camera->onCameraError error = unkown error.
D/AndroidRuntime( 4283): Shutting down VM
W/dalvikvm( 4283): threadid=1: thread exiting with uncaught exception (group=0x4178f700)
I/InputDispatcher( 2577): Dropping event because there is no touched window.
E/AndroidRuntime( 4283): FATAL EXCEPTION: main
E/AndroidRuntime( 4283): java.lang.RuntimeException: Unable to resume activity {com.ucloud.ulive.example/com.ucloud.ulive.example.PublishDemo}: java.lang.NullPointerException
E/AndroidRuntime( 4283):        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2790)
E/AndroidRuntime( 4283):        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2819)
E/AndroidRuntime( 4283):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2266)
E/AndroidRuntime( 4283):        at android.app.ActivityThread.access$600(ActivityThread.java:141)
E/AndroidRuntime( 4283):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
E/AndroidRuntime( 4283):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 4283):        at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 4283):        at android.app.ActivityThread.main(ActivityThread.java:5103)
E/AndroidRuntime( 4283):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 4283):        at java.lang.reflect.Method.invoke(Method.java:525)
E/AndroidRuntime( 4283):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
E/AndroidRuntime( 4283):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
E/AndroidRuntime( 4283):        at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 4283): Caused by: java.lang.NullPointerException
E/AndroidRuntime( 4283):        at com.ucloud.ulive.av.f.setAudioCPUFilter(SourceFile:16205)
E/AndroidRuntime( 4283):        at com.ucloud.ulive.example.PublishDemo.initStreamingEnv(PublishDemo.java:397)
E/AndroidRuntime( 4283):        at com.ucloud.ulive.example.PublishDemo.uliveOnResume(PublishDemo.java:438)
E/AndroidRuntime( 4283):        at com.ucloud.ulive.example.PublishDemo.onResume(PublishDemo.java:450)
E/AndroidRuntime( 4283):        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1192)
E/AndroidRuntime( 4283):        at android.app.Activity.performResume(Activity.java:5211)
E/AndroidRuntime( 4283):        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2780)
E/AndroidRuntime( 4283):        ... 12 more
I/InputDispatcher( 2577): Dropping event because there is no touched window.
V/WindowManager( 2577): Clear freezing of Token{41a60440 ActivityRecord{41eca610 u0 com.ucloud.ulive.example/.PublishDemo}}: hidden=true freezing=false
V/WindowManager( 2577): Clear freezing of Token{42067c00 ActivityRecord{41bcf4d8 u0 com.ucloud.ulive.example/.MainActivity}}: hidden=false freezing=false
W/ActivityManager( 2577):   Force finishing activity com.ucloud.ulive.example/.PublishDemo
V/WindowManager( 2577): setAppVisibility(Token{41a60440 ActivityRecord{41eca610 u0 com.ucloud.ulive.example/.PublishDemo}}, visible=false): mNextAppTransition=0x1006 hidden=true hiddenRequested=false
W/ActivityManager( 2577):   Force finishing activity com.ucloud.ulive.example/.MainActivity
I/Process ( 4283): Sending signal. PID: 4283 SIG: 9
I/InputDispatcher( 2577): Dropping event because there is no touched window.
I/InputDispatcher( 2577): Dropping event because there is no touched window.
I/WindowState( 2577): WIN DEATH: Window{41a867d0 u0 com.ucloud.ulive.example/com.ucloud.ulive.example.MainActivity}
I/ActivityManager( 2577): Process com.ucloud.ulive.example (pid 4283) has died.
I/InputDispatcher( 2577): Dropping event because there is no touched window.
I/WindowState( 2577): WIN DEATH: Window{41c05070 u0 Toast}
V/WindowManager( 2577): setAppVisibility(Token{41cd0d00 ActivityRecord{41c25cf8 u0 com.android.launcher/com.android.launcher2.Launcher}}, visible=true): mNextAppTransition=0x1006 hidden=true hiddenRequested=true
V/WindowManager( 2577): Done at AppWindowToken{41c3e1f8 token=Token{41cd0d00 ActivityRecord{41c25cf8 u0 com.android.launcher/com.android.launcher2.Launcher}}} -- full screen, return -1
V/WindowManager( 2577): Application requested orientation -1, got rotation 3 which has compatible metrics
V/WindowManager( 2577): Done at AppWindowToken{41c3e1f8 token=Token{41cd0d00 ActivityRecord{41c25cf8 u0 com.android.launcher/com.android.launcher2.Launcher}}} -- full screen, return -1
I/WindowStateAnimator( 2577): createSurface WindowStateAnimator{41c2f998 com.android.launcher/com.android.launcher2.Launcher}: mDrawState=DRAW_PENDING
V/WindowManager( 2577): Done at AppWindowToken{41c3e1f8 token=Token{41cd0d00 ActivityRecord{41c25cf8 u0 com.android.launcher/com.android.launcher2.Launcher}}} -- full screen, return -1
V/WindowManager( 2577): Eval win Window{41c2f400 u0 com.android.launcher/com.android.launcher2.Launcher}: isDrawn=false, isAnimating=true
V/WindowManager( 2577): Not displayed: s=Surface(name=com.android.launcher/com.android.launcher2.Launcher) pv=true mDrawState=1 ah=false th=false a=false
E/BufferQueue( 2282): [com.android.launcher/com.android.launcher2.Launcher] dequeueBuffer: can't dequeue multiple buffers without setting the buffer count
W/InputMethodManagerService( 2577): Got RemoteException sending setActive(false) notification to pid 4283 uid 10039
V/WindowStateAnimator( 2577): finishDrawingLocked: mDrawState=COMMIT_DRAW_PENDING WindowStateAnimator{41c2f998 com.android.launcher/com.android.launcher2.Launcher} in Surface(name=com.android.launcher/com.android.launcher2.Launcher)
V/WindowManager( 2577): Eval win Window{41c2f400 u0 com.android.launcher/com.android.launcher2.Launcher}: isDrawn=true, isAnimating=true
V/WindowManager( 2577): tokenMayBeDrawn: AppWindowToken{41c3e1f8 token=Token{41cd0d00 ActivityRecord{41c25cf8 u0 com.android.launcher/com.android.launcher2.Launcher}}} freezingScreen=false mAppFreezing=false
I/WindowManager( 2577):   SURFACE SHOW (performShowLocked): Window{41c2f400 u0 com.android.launcher/com.android.launcher2.Launcher}
V/WindowManager( 2577): Done at AppWindowToken{41c3e1f8 token=Token{41cd0d00 ActivityRecord{41c25cf8 u0 com.android.launcher/com.android.launcher2.Launcher}}} -- full screen, return -1
V/WindowManager( 2577): Eval win Window{41c2f400 u0 com.android.launcher/com.android.launcher2.Launcher}: isDrawn=true, isAnimating=false
V/WindowManager( 2577): tokenMayBeDrawn: AppWindowToken{41c3e1f8 token=Token{41cd0d00 ActivityRecord{41c25cf8 u0 com.android.launcher/com.android.launcher2.Launcher}}} freezingScreen=false mAppFreezing=false
V/WindowManager( 2577): Done at AppWindowToken{41c3e1f8 token=Token{41cd0d00 ActivityRecord{41c25cf8 u0 com.android.launcher/com.android.launcher2.Launcher}}} -- full screen, return -1
binder: 2577:2591 transaction failed 29189, size 80-0
W/NotificationService( 2577): Object died trying to hide notification android.app.ITransientNotification$Stub$Proxy@41a87f88 in package com.ucloud.ulive.example
W/audio_hw_primary( 3699): do_out_standby... 1087932016

**Comment by michaelchen11** [comment]
请问使用的Demo是哪个版本？

**Comment by yanghui1** [comment]
摄像头可以用其他apk能打开，同一个摄像头，同一个ａｐｋ．在android４.４版本上不会退出

**Comment by tanliwen** [comment]
@yanghui1 了解。方便提供邮箱，发个debug版本给你，联合调试一下吗。

**Comment by yanghui1** [comment]
@tanliwen  412724279@qq.com  可以qq随时沟通！一直在线中！

**Comment by yanghui1** [comment]
@tanliwen  qq就是412724279
