### ISSUE TITLE
开始一会儿会自动crash，不清楚什么情况，望回复

### ISSUE THREAD

**Issue by liyuzhao** [umdk/UCDLive_Android#3]
另，我想在开始直播后，主播可以切换大小，是否可以，怎样调用才可以，我测试了并不能等比例缩小。是否需要调用其他API？急急急！！！

魅族：android 5.1

12-07 20:52:57.909 11452-11452/? E/StartLiveActivity: lifecycle->demo->onSurfaceTextureSizeChanged width = 600, height = 600
12-07 20:52:59.572 11452-11452/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.easemob.ulivetest, PID: 11452
                                                   java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
                                                       at java.util.regex.Matcher.reset(Matcher.java:177)
                                                       at java.util.regex.Matcher.<init>(Matcher.java:90)
                                                       at java.util.regex.Pattern.matcher(Pattern.java:297)
                                                       at com.ucloud.ulive.a.g$b.handleMessage(SourceFile:1156)
                                                       at android.os.Handler.dispatchMessage(Handler.java:111)
                                                       at android.os.Looper.loop(Looper.java:194)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5838)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1009)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:804)

**Comment by michaelchen11** [comment]
这边报的是一个NullPointerException错误，请检查调用Matcher.reset的方法时是否传入了空值

**Comment by michaelchen11** [comment]
请检查是否设置了直播的url

**Comment by liyuzhao** [comment]
你好，startRecording后， 我更改父容器的width和height， 图像并没有缩放，而是显示其中一部分，但是我startRecording前修改，就可以，我想实现录播时，切换父容器的width和height，子容器（UAspectFrameLayout的宽和高都是match_parent）更改跟着缩放。我经过测试都是开始后就不行了，需要stop任何再start才行，我看了你们手机横竖屏切换的代码，也是先stop然后再start，这样流会中断的，能否stop和start直接跟着缩放呢，有没有解决方案？望告知，急急急！！谢谢！
