### ISSUE TITLE
设置1080P分辨率异常

### ISSUE THREAD

**Issue by zy1301529626** [umdk/UCDLive_Android#9]
代码设置位置:

```

    @Override
    public USize[] onPreviewSizeChoose(int cameraId, List<USize> cameraSupportPreviewSize) {
        USize[] sizes = new USize[2];
        sizes[1] = new USize(1920, 1080);
        sizes[2] = new USize(1920, 1080);
        return sizes;
//        Log.i(TAG, "lifecycle->demo->camera->onPreviewSizeChoose.");
//        return null;
    }
```
错误异常:

```
03-02 09:10:42.087 28770-28770/com.ucloud.ulive.example E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: com.ucloud.ulive.example, PID: 28770
                                                                          java.lang.RuntimeException: Unable to resume activity {com.ucloud.ulive.example/com.ucloud.ulive.example.PublishDemo}: java.lang.NullPointerException: Attempt to read from field 'java.util.concurrent.locks.Lock com.ucloud.ulive.av.a.b.e' on a null object reference
                                                                              at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3110)
                                                                              at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3141)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2488)
                                                                              at android.app.ActivityThread.access$900(ActivityThread.java:153)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:148)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5441)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
                                                                           Caused by: java.lang.NullPointerException: Attempt to read from field 'java.util.concurrent.locks.Lock com.ucloud.ulive.av.a.b.e' on a null object reference
                                                                              at com.ucloud.ulive.av.f.setAudioCPUFilter(SourceFile:16205)
                                                                              at com.ucloud.ulive.example.PublishDemo.initStreamingEnv(PublishDemo.java:397)
                                                                              at com.ucloud.ulive.example.PublishDemo.uliveOnResume(PublishDemo.java:438)
                                                                              at com.ucloud.ulive.example.PublishDemo.onResume(PublishDemo.java:450)
                                                                              at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1259)
                                                                              at android.app.Activity.performResume(Activity.java:6379)
                                                                              at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3099)
                                                                              at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3141)?
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2488)?
                                                                              at android.app.ActivityThread.access$900(ActivityThread.java:153)?
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)?
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)?
                                                                              at android.os.Looper.loop(Looper.java:148)?
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5441)?
                                                                              at java.lang.reflect.Method.invoke(Native Method)?
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)?
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)?
```

**Comment by tanliwen** [comment]
@zy 数组越界了！sizes[0]=预览大小 sizes[1]=编码大小

**Comment by zy1301529626** [comment]
但是问题是空指针啊，该如何写？

**Comment by tanliwen** [comment]
@zy 空指针是因为你没有正确初始化你需要自定义分辨率的数组啊，我们demo都有写的。你把数组初始化改为sizes[0] sizes[1]啊，这个数组长度下标是从0开始的啊，你这么赋值内部怎么拿到正确的值呢？

**Comment by zy1301529626** [comment]
写错了 不好意思

**Comment by zy1301529626** [comment]
@Override
    public USize[] onPreviewSizeChoose(int cameraId, List<USize> cameraSupportPreviewSize) {
        USize[] sizes = new USize[2];
        sizes[0] = new USize(1920, 1080);
        sizes[1] = new USize(1920, 1080);
        Log.i(TAG, "lifecycle->demo->camera->onPreviewSizeChoose.");
        return sizes;
    }
还是会崩溃 依旧是那个异常

**Comment by tanliwen** [comment]
@zy1301529626 你先用我们demo试试吧

**Comment by zy1301529626** [comment]
就是在你们的demo上改的

**Comment by tanliwen** [comment]
@zy1301529626 什么版本， 在最新demo试过是没问题的，有改初始化流程吗，我们Demo没做任何修改，只是改了预览返回值？
  Caused by: java.lang.NullPointerException: Attempt to read from field 'java.util.concurrent.locks.Lock com.ucloud.ulive.av.a.b.e' on a null object reference
                                                                              at com.ucloud.ulive.av.f.setAudioCPUFilter(SourceFile:16205)
                                                                              at com.ucloud.ulive.example.PublishDemo.initStreamingEnv(PublishDemo.java:397)
                                                                              at com.ucloud.ulive.example.PublishDemo.uliveOnResume(PublishDemo.java:438)
                                                                              at com.ucloud.ulive.example.PublishDemo.onResume(PublishDemo.java:450)
                                                                              at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1259)
                                                                              at android.app.Activity.performResume(Activity.java:6379)
                                                                              at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3099)
                                                                              at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3141)?
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2488)?
                                                                              at android.app.ActivityThread.access$900(ActivityThread.java:153)?
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)?
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)?
                                                                              at android.os.Looper.loop(Looper.java:148)?
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5441)?
                                                                              at java.lang.reflect.Method.invoke(Native Method)?
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)?
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628

这里和

**Comment by zy1301529626** [comment]
换用最新的demo，修改后还是会崩溃

**Comment by michaelchen11** [comment]
@zy1301529626 
1. 先确认最新demo是否能正常运行
2. 集成sdk请参考文档 https://github.com/umdk/UCDLive_Android/wiki

**Comment by zy1301529626** [comment]
USize[] sizes = new USize[2];
        sizes[0] = new USize(1920, 1080);
        sizes[1] = new USize(1920, 1080);//设置1920*1080后，点击Demo_publish 就会崩溃
设置其他分辨率不会崩溃

**Comment by zy1301529626** [comment]
demo里的sdk是最新的吧

**Comment by tanliwen** [comment]
@zy1301529626
1. 使用硬编？软编暂不支持
2 .崩溃日志一样？+机型？
3. public USize[] onPreviewSizeChoose(int cameraId, List<USize> cameraSupportPreviewSize)｛｝｛
     cameraSupportPreviewSize ？ 支持 1920x1080
｝

**Comment by tanliwen** [comment]
@zy1301529626  lifecycle->demo->camera->onCameraError error = camera no support preview size:1920x1080 按道理有错误日志打印的？麻烦找台支持1080p的机器试，cameraSupportPreviewSize集合返回了当前设备支持的分辨率，设置之前请判断当前设备是否支持.

**Comment by zy1301529626** [comment]
录制是否需要用户手机的摄像头支持1080P的视频录制

**Comment by tanliwen** [comment]
@zy1301529626 是的。

**Comment by zy1301529626** [comment]
@tanliwen 设置1080P后，进入录制界面，点击开始，闪退出录制界面 不显示崩溃信息

**Comment by zy1301529626** [comment]
@tanliwen 播放端正在直播播放,观看端观看这个直播源报-10000错误,这个error的意思是？

**Comment by tanliwen** [comment]
@zy1301529626 
播放器sdk参考文档
https://github.com/umdk/UCDMediaPlayer_Android/wiki/5-%E5%8A%9F%E8%83%BD%E4%BD%BF%E7%94%A8#5.1
